org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Fix for AndroidLocationsBuildService error on Windows/OneDrive
android.user.home=C:\\AgentProject\\.android
systemProp.android.user.home=C:\\AgentProject\\.android
android.sdk.home=C:\\AgentProject\\.android
systemProp.android.sdk.home=C:\\AgentProject\\.android
android.suppressUnsupportedCompileSdk=35
